redhat-developer-tooling/developer-platform-install

browser/model/vagrant.js
Apparently some windows versions don't allow powershell scripts to be run by default. This should allow the vagrant installation to bypass that.
=> Allow vagrant install to run powershell scripts

browser/pages/account/controller.js
Fix adds __pathname/.. to package.json file to resolve it correctly.
=> JBDS-3682 Online installer reports missing package.js file

browser/main.js, browser/model/cygwin.js, browser/model/vagrant.js, browser/services/data.js, test/unit/model/cygwin-test.js, test/unit/services/data-test.js
returning cygwin back for these reasons:
- it is the only ssh/rsync implementation that can be used to
configure sshd service and then use version 1.0.0 of vagrant-sshfs
to   mount the users home directory into the VM (see JBDS-3671 for
details) ;
- it works with latest vagrant release 1.8.1, mingw based ssh/rsync
does not. This is the going tombe a problem in case someone has it
already installed and decided to skip vagrant installation and
use preinstalled one.
=> JBDS-3647 Investigate why we are including both cygwin and mingw

browser/main.js, browser/model/cdk.js, browser/model/jbds.js, browser/services/data.js, test/unit/model/cdk-test.js, test/unit/model/jbds-test.js, test/unit/services/data-test.js
~~Still need to check if we now can get rid of the Vagrantfile provided by the https://github.com/redhat-developer-tooling/openshift-vagrant~~
Update: Update to CDK Beta5 + use Vagrantfile provided by CDK 
See https://issues.jboss.org/browse/JBDS-3656
=> JBDS-3690 Update to CDK Beta5

browser/model/jdk-install.js, browser/model/virtualbox.js, requirements.json
Fix renames:
1. VirtualBox-5.0.4.exe to virtualbox.exe
2. jdk8.zip to jdk.zip
=> JBDS-3702 No numbers for VirtualBox and JDK key in requirements.json

browser/model/cdk.js
Current implementation fails if cdkv2 box already exists, this fix
add remove command wich removes box befor registering new one.
=> JBDS-3654 remove box with the same name for registering new one

browser/services/data.js, test/unit/model/jbds-test.js, test/unit/services/data-test.js
Fix moves Developer Studio default installtion folder to developer-studio
and updates unit tests to pass.
=> JBDS-3741 Developer Studio should install under developer-studio

browser/model/cygwin.js, test/unit/model/cygwin-test.js
Fix adds additional command to cygwin install code to copy
downloaded setup file to cygwin target dir with original name.
=> JBDS-3742 Cygwin setup executable should be installed as well

browser/main.js, browser/model/helpers/downloader.js, browser/model/helpers/hash.js, browser/model/vagrant.js, browser/model/virtualbox.js, browser/pages/install/controller.js
This fix adds checksum only for vagrant.msi and virtualbox.exe files all other files downloaded during build with checksum verification against sha256 hex stored in requirements.js
=> JBDS-3800 Check SHA256 checksums for downloaded vagrant and virtualbox

browser/pages/location/controller.js
Fix makes dialog modal for main installer window, so there is no
way to select it.
=> JBDS-3696 Browse buttons should not respond when a file dialog is opened

browser/services/data.js, package.json
Fix creates target folder with mkdirp.sync method.
=> JBDS-3835 Installer: recursively installation folder creation needed

browser/model/jdk-install.js, browser/pages/confirm/confirm.html, browser/pages/confirm/controller.js
Disable OpenJDK checkbox in case no JavaVM detected or detected version is invalid.
Prefer detected java if detected version is valid..
=> JBDS-3803 Add JavaVM version detection and validation

gulpfile.js
why hardcode paths when the variables are already defined - one path was in fact wrong
=> Fix path for cleanup

browser/pages/confirm/controller.js
No message if nothin is detected.
'that meets the requirements' removed.
=> JBDS-3819 Showing that we detected 0 existing components is useless

browser/model/jdk-install.js
Fix contains new regex template to match previous and current formats
=> JBDS-4002 OpenJDK detection does not work for build 1.8.0_101

browser/bootstrap.js
This PR adds context menu to show chrome devtools inside installer window.
=> JBDS-3834 Install fail - what next?

gulpfile.js, requirements.json
Always include cygwin.exe in installer for one big reason. If file gets updated to new one, there is no archived copy of previous one and that means redirect we use does not help.
=> JBDS-4031 error sha check for downloaded cygwin

requirements.json
Fix updates version shown in installer to 2.6.0 and place direct link
instead of redirect because cygwin installer (size under 1M) will be
always included in online and bunded installer after
https://issues.jboss.org/browse/JBDS-4031 is fixed
It means it is  going to be alway downloaded during the build.
=> JBDS-4043 Update cygwin version to 2.6.0

browser/model/helpers/util.js, browser/model/jdk-install.js, browser/pages/confirm/confirm.html
Fix implements:
1. Check if OpenJDK MSI package installed, using the same query
used by uninstall.ps1. It sets flag openJdkMsi on JdkInstall
instance. This flag blocks OpenJDK selection for installation
to avoid possible installation errors in case msi cannot update
already installed OpenJDK;
2. Disabling for Back ad Next buttons on Confirmation page until
detection is finished.
=> JBDS-4007 Need a new check for existing OpenJDK installed as MSI

gulpfile.js, requirements.json
Fix updates file name to one without timestamp,
because timestamp wa removed before publishing to CDN/DM
=> Update link to DevStudio standalone installer

browser/model/jdk-install.js
Fix adds to the powershell execution:
* -Noneinteractive option;
* exit(0) call in the end of the script
=> JBDS-4048 OpenJDK detection stuck

uninstaller/uninstall.ps1
Fix corrects target folder path being used for
filtering Path variable entries. It changes root folder
to be one level up from uninstaller folder.
=> JBDS-4047 uninstaller does not clean up path

gulpfile.js, protractor-conf.js
Fix removes unused local var and updates rootbuildfolder to be
named after current platform-arch, rather than hardcoded to
dist/win. Tis fix after merge will require to update nightly
build publishing config on central CI.
=> Update hardcoded dist/win folder to be based on current platform/arch

browser/model/jbds.js, test/unit/model/jbds-test.js
Use java (no extension) on all platforms and let windows find .exe
file.
=> JBDS-4083 update devstudio installer start to support all platforms

browser/model/jbds-autoinstall.js
Fix adds windows suffix 'w.exe' for java executable.
=> JBDS-4107 Devstudio install config has wrong java path on windows

browser/model/cdk.js, browser/model/cygwin.js, browser/model/installable-item.js, browser/model/jbds.js, browser/model/jdk-install.js, browser/model/vagrant.js, browser/model/virtualbox.js, test/unit/model/cdk-test.js, test/unit/model/cygwin-test.js, test/unit/model/installable-item-test.js, test/unit/model/jbds-test.js, test/unit/model/jdk-install-test.js, test/unit/model/vagrant-test.js, test/unit/model/virtualbox-test.js
Fix adds verification for downloaded files in temp folder and
if sha is the same installer uses those files instead of downloading
them again.
=> JBDS-4080  Avoid to redownload everything on each install

browser/model/cdk.js
Fix skips windows specific code to let CDK installer
finish installation without configuring PATH env variable.
=> JBDS-4120 CDK Installer does not work on Mac OS X

browser/model/cdk.js
Fix updates the code to use static method to get the key instead of this.key.
=> JBDS-4139 undefined key used in cdk whenlogging PATH env var value

browser/model/vagrant.js
Fix remoses execution setx from vagrant.js, because it is CDK
responsibility to set it up.
=> JBDS-4138 Remove setx VAGRANT_DETECTED_OS setup from vagrant installer

browser/model/cdk.js, test/unit/model/cdk-test.js
Fix updates name to 'PATH" because it works for OS X and Window
=> JBDS-4140 env['Path'] doesn't work for child_process on OS X

browser/model/jdk-install.js
Fix removes '()' from Promise().resolve() call and updates
parameter passed to installer.succeed to true instead of string
found in file which might be falsy
=> Code clenup in JdkInstall class

browser/model/cdk.js, browser/services/platform.js, test/unit/model/cdk-test.js, test/unit/services/platform-test.js
Fix restores previous approach and pass copy of process.env to
child process.
=> JBDS-4161 VAGRANT_HOME is not set for vagrant plugin installation

browser/directives/breadcrumb.js, browser/directives/pathValidator.js, browser/directives/progressBar.js, browser/main.js, browser/model/cdk.js, browser/model/cygwin.js, browser/model/helpers/util.js, browser/model/jbds-autoinstall.js, browser/model/jbds.js, browser/model/jdk-install.js, browser/model/vagrant.js, browser/model/virtualbox.js, browser/pages/confirm/controller.js, browser/pages/location/controller.js, browser/pages/start/controller.js, browser/services/data.js, browser/services/request.js
Fix migrates replaces process.env and process.platform
to correspondein Platform.ENV and Platform.OS class properties
to let test methods related to environments and specific OS.
See examples in cdk-tests createEnvironment tests.
=> Code Cleanup: use Platform.OS and Platform.ENV throughout browser/**

uninstaller/uninstall.ps1
In case some files cant get deleted due to too long path, use robocopy (available in Win 7+) to purge the directories.
=> JBDS-4119 Uninstaller - remove files with too long path

requirements-win32.json
FIx updates format for Java Version in requirements-win32.json file
=> JBDS-4165 Invalid Java Version '1.8.0.111' error in devtools console

requirements-darwin.json
Fix includes update for macOS client tools.
Mac client tools have been rebuilt on top of Go 1.7 to fix
various issues related to the OS X Sierra update.
=> Update oc client tools for macOS

requirements-darwin.json, requirements-win32.json
Fix includes direct links to avoid downloading after
new nightly version is published during demo
=> Update DevStudio build to latest nightly build

browser/main.js
Fix introduces DM_STAGE_HOST env variable which value
replaces developers.redhat.com host in DM manager URL's.
=> JBDS-4125 Replace developers.redhat.com to stage host in DM links

browser/model/installable-item.js, browser/model/jdk-install.js, test/unit/model/jdk-install-test.js
Fix adds platform specific tests to JDK unit tests,
corrects wrong expect calls and gets coverage to
back to 100%.
=> Improve code coverage for JDK Installer

browser/services/platform.js, test/unit/services/platform-test.js
Fix adds check if default option is present. It runs default
function if provided or returns undefined.
=> Platform.identify fails if no match for platform and no default

browser/model/vagrant.js, browser/model/virtualbox.js
Fix changes location set for install options. On windows
location stays the same, but on macOS both Vagrant and Virtualbox
adds soft  links into /usr/loca/bin directory.
=> JBDS-4174 Install Vagrant and Virtualbox on macOS

browser/model/jdk-install.js, test/unit/model/jdk-install-test.js
Fix removes extra parameter from Util.writeFile call and changes
the tests to fail if Util.writeFile called with wrong parameters.
=> JBDS-4196 MSI installed OpenJDK detection does not work

browser/model/helpers/installer.js
Fix makes buffer size twice bigger to avoid exceeding
maxBuffer on slow macOS machines.
=> Increase buffer size to avoid exceeding maxBuufer

gulp-tasks/dist-darwin.js, gulpfile.js, package.json
Fix:
* refactors mac build to use electron-builder API
instead of configuration and implements gulp 'dist' task
for macOS
* includes version update from GA to Alpha1 for macOS
=> JBDS-4193 Build Bundle Installer for macOS

README.md, package.json
Fix updates gulp to full relative path in package.json
to avoid addition step with gulp global installation to
configure development environment.
It also removes gulp global installation step from readme.md.
=> Update gulp to relative path ./node_modules/.bin/gulp

test/unit/model/cygwin-test.js
Fix removes done() call to fix the error.
=> Fix promise rejection error in cygwin tests

browser/model/jdk-install.js, requirements-win32.json
Fix updates public and internal links for OpenJDK release
and adds extra parameter to msiexec to install jdk and updater.
=> JBDS-4224 Update OpenJDK to latest available release

README.md, gulp-tasks/tests.js, gulpfile.js
This allows to run specific tests in file not the whole suite.
It accepts globe patterns as well.
=> Add spec-file parameter to unit-test gulp task

test/unit/services/logger-test.js
Fix adds after() method where Logger.getIpcRenderer method restored to
original.
=> Restore logger to original state after tests

browser/pages/confirm/controller.js
I couldn't find any practical use for it and it just clutters the console.
=> Remove debug error from cdk watcher

browser/model/cdk.js
so the bundled installer can find the file
=> JBDS-4245 rename minishift zip to cdk to have the filenames match

browser/model/virtualbox.js, test/unit/model/virtualbox-test.js
Because minishift was complaining host-only adapter was not installed.
=> JBDS-4240 Add host-only adapter to virtualbox installation

test/unit/model/installable-item-test.js
so it doesn't create a file every time the test runs
=> Stub out file creation in installable-item test

gulpfile.js
Remove dependency files that are not declared in requirements.json before bundling them, so they don't get used after file name change, etc. Requires #500 to be merged first for the filenames to match requirements.json
=> JBDS-4249 remove outdated cached dependencies before build

browser/directives/progressBar.html, browser/model/cdk.js, browser/model/helpers/downloader.js, browser/model/installable-item.js, browser/pages/install/controller.js, test/unit/model/cdk-test.js, test/unit/model/helpers/downloader-test.js, test/unit/model/installable-item-test.js, test/unit/model/jdk-install-test.js
Adding new statuses for the two possible sha checks, since otherwise downloads would seem to be stuck for a while on 0 or 100%:
- 'Verifying Existing Download' - for checking existing downloaded files
- 'Verifying Download' - for sha check after download finishes
Both will be presented with an indeterminate bar.
=> JBDS-4155 Add progress statuses for checksum verification

browser/model/cdk.js, browser/model/helpers/installer.js, package.json, test/unit/model/helpers/installer-test.js
Fix adds:
* check for archive extension in Installer.unzip
* targz unpack for tar.gz files
* prefix to copy minishift.exe only without darwin-amd64 folder
=> JBDS-4250 CDK installer: latest minishift installer fails on MacOS

browser/directives/progressBar.html, browser/directives/progressBar.js, browser/pages/install/controller.js, browser/pages/install/install.html, test/ui/install-test.js, test/unit/pages/install/controller-test.js
* Pass whole ProgressStatus instance to the directive
* Use ng-repeat to show progress bars for components being installed
* Simplify call for angular digest when status or progress changes
* update ui and unit tests to pass
=> Progress bar refactoring

browser/pages/confirm/controller.js, test/unit/model/cygwin-test.js
This change contains minor fixes related to promisified detection methods. It:
1. Removes wrapping promise for installer#detectExistingInstall call, which is not required because it now returns promise instance;
2. Fix one test case to use promise instead of callback.
=> JBDS-4223 Promisify Installer detection methods

browser/model/cdk.js, browser/model/jbds.js
Fix removes detectExistingInstall metjods because base class already
has the same default implementation.
=> Remove detectExistinInstall method from cdk and devstudio installer

package.json
request           2.80.0  →  2.81.0
babel-core        6.23.1  →  6.24.0
electron-builder  15.1.1  →  15.4.3
mock-fs            4.1.0  →   4.2.0
rcedit             0.7.0  →   0.8.0
yargs              7.0.1  →   7.0.2
=> Update dependencies to the latest

test/unit/directives/breadcrumb-test.js, test/unit/directives/progressbar-test.js
This fix tests only loading with fake template content, because with original
it gets error:
https://docs.angularjs.org/error/$sce/insecurl?p0=directives%2FprogressBar.html
=> Increase directives unit test coverage

browser/main.js, browser/model/cdk.js, browser/model/cygwin.js, browser/model/devstudio.js, browser/model/jdk-install.js, browser/model/virtualbox.js, browser/pages/confirm/confirm.html, browser/pages/confirm/controller.js, browser/services/componentLoader.js, browser/services/metadata.js, requirements.json, test/unit/model/cdk-test.js, test/unit/model/cygwin-test.js, test/unit/model/devstudio-test.js, test/unit/model/jdk-install-test.js, test/unit/model/virtualbox-test.js, test/unit/pages/confirm/controller-test.js, test/unit/pages/install/controller-test.js, test/unit/pages/start/controller-test.js, test/unit/services/componentLoader-test.js, test/unit/services/data-test.js
Rewritten the hardcoded init for model classes into something more "dynamic". Quite a big change, so here is how it works:
- everything (almost) is now loaded from requirements.json - it maps strings to class names and instantiates them using javascript magic (see ComponentLoader and DynamicClass for reference)
- there is some default ordering of the installation sequence if all the components are present
- if some component is omitted, the loader squashes the sequence = replaces the component with the components that depended on it (e.g. if cygwin is omitted, cdk installs after virtualbox/hyper-v), the same principle is used for the checkboxModel in confirmController
- the model constructors are fed arguments directly from requirements.json, therefore the ordering of the properties in …
=> JBDS-4301 Allow loading subset of components from requirements.json

main/index.js, main/menu.js
The template is very much copied from the one electron uses. Now it should be possible to use commands like copy/cut/paste etc.
=> JBDS-4323 Enable main menu on mac

test/unit/model/kompose-test.js
some of the async code started disrupting other tests - fixed by stubbing the methods properly
=> Fix unstubbed method calls in unit tests

test/unit/model/kompose-test.js
got an error in ci: Error: ENOENT: no such file or directory, open 'temporaryFolder/kompose.exe'
suggests some fs operation was run in the test -> mock the fs
=> Mock fs in tests

requirements.json
The extension check fails on mac with dots in file name.
=> JBDS-4372 Remove dots from minishift filename

package.json
Add
``` JavaScript
debugger;
```
line in your tests where you want to start debugging and run
``` Shell
npm run debug-test test/unit/
```
Then open url printed in stdout in browser and hit run button in
Devtools toolbar.
=> Add ability to debug tests

browser/model/jdk-install.js
Fix skips msi detection for linux and darwin platforms
=> Java detection does not work under linux

browser/pages/account/controller.js
This fix is temporary solution for cases when there are
problems with proxy configuration. There is no log file yet
so let's out it as error to chromium console.
=> JBDS-4301 Print login error to chromium console

gulp-tasks/dist-darwin.js, gulp-tasks/dist-win32.js, gulpfile.js, requirements.json
- Something/someone keeps deleting devstudio builds from the staging server.
- update-requirements was called twice in most cases, update-package on mac is now part of update-requirements, so I deleted that one as well
=> Update devstudio link + remove duplicated build steps

browser/model/jdk-install.js, test/unit/model/jdk-install-test.js
Thankfully, one can find if java is available by calling /usr/libexec/java_home first
=> JBDS-4419 Skip calling java if no jvm is available

browser/pages/confirm/confirm.html, requirements.json
It should now be apparent users need to install Oracle JDK on Mac because we are bound by licence issues. And the download link is fixed as well.
=> JBDS-4420 Clarify Java instructions for Mac

browser/services/data.js, browser/services/metadata.js, gulp-tasks/dist-darwin.js, gulp-tasks/dist-win32.js, gulpfile.js, test/unit/model/cdk-test.js, test/unit/model/hyperv-test.js, test/unit/model/installable-item-test.js, test/unit/services/data-test.js
so that it can be called repeatedly on the same set of requirements. Basically, loadMetadata would change the data stored in require('requirements.json') and since require caches the result, it would never load the original requirements again. 
Now it should not touch the original content and instead create a working copy.
=> Clone requirements when calling loadMetadata

gulp-tasks/tests.js, gulpfile.js, main/index.js, protractor-conf.js, test/system/windows/runTests.ps1
- unpacking now works properly with bundled installer (added a switch for it)
- added the bundle folder as a chrome argument to protractor (but it keeps prepending dashes, so that's why there is the replace part - but only if the string actually starts with '--')
=> Fix system test launch for bundled installer

browser/model/jbosseap-autoinstall.js, browser/model/jbosseap.js, test/unit/model/jbosseap-test.js
Fix is getting rid of jbosseap-install.xml.properties file by moving
password configuration to xml file itself.
=> JBoss EAP password config moved to xml configuration file

browser/model/cdk.js, browser/model/cygwin.js, browser/model/devstudio-autoinstall.js, browser/model/devstudio.js, browser/model/hyperv.js, browser/model/installable-item.js, browser/model/jbosseap.js, browser/model/jdk-install.js, browser/model/kompose.js, browser/model/virtualbox.js, browser/pages/confirm/confirm.html, browser/pages/confirm/controller.js, browser/services/componentLoader.js, browser/services/data.js, gulp-tasks/dist-win32.js, gulp-tasks/download.js, gulp-tasks/https-server.js, package.json, requirements.json, test/ui/start-test.js, test/unit/model/devstudio-test.js, test/unit/model/kompose-test.js, test/unit/pages/confirm/controller-test.js, test/unit/services/componentLoader-test.js
This fix includes prep changes required for Fuse Tools Installer:
* moves installer ordering configuration from code to
requirements.json file;
* introduce additional parameter for devstudio installer to allow fuse
installer to provide correct key value;
* introduces additional parameters to list additional IUs to install;
* swithces to factory metod fromJason to create installer instances;
* add 'requires' attributes to installer's configuration, but those are
not used yet on confirmation page.
=> JBDS-4423 Refactor Installer services: dependencies resolution and installation ordering

gulp-tasks/dist-win32.js
so that bundled installer may work with different file names of the inner archive
=> JBDS-4455 Update 7zip config for bundled installer on build

browser/model/devstudio.js
Fix add extra check for bundled files and init downloadedFile location
with bundled file.
=> JBDS-4463 Bundle Installer fails to install fuse tools

browser/model/jbossfuse.js, browser/model/jbossfusekaraf.js, test/unit/model/fuseplatformkaraf-test.js
Fix attaches runtime detection configuration to installation
of fuse tools.
=> JBDS-4464 Fuse Platform does not get added to runtime detection

browser/model/devstudio.js, browser/model/jbosseap.js, browser/model/jbossfuse.js, browser/model/jbossfusekaraf.js, browser/model/jdk-install.js, browser/pages/confirm/controller.js, browser/services/data.js, test/unit/model/devstudio-test.js, test/unit/model/fuseplatformkaraf-test.js, test/unit/model/jbosseap-test.js, test/unit/model/jbossfuse-test.js, test/unit/model/jbossfusekaraf-test.js, test/unit/pages/confirm/controller-test.js, test/unit/services/data-test.js
This fix:
1. Removes not deeded listeners for cmponents required OpenJDK
to be installed first, because install ordering is already taking
care of it
2. Fix unit test errors under macOS
=> JBDS-4469 Some servers added to runtime detection only with fuse tools

browser/main.js, browser/pages/confirm/controller.js, test/unit/pages/confirm/controller-test.js
Fix moves loading the list of components available for installation
to confirmation controller in preparation to loading configuration
from remote location.
=> Move loading the installable components to confirm page

browser/model/devstudio-autoinstall.js
When DevStudio installed with additional IUs (Installation Units) it
is always indicate that devstudio itself installed as requirement,
hence shortcuts are created already and can be skipped from
automated install configuration.
=> JBDS-4497 skip creating shortcts in case of installing additional IUs

browser/directives/progressBar.html, browser/pages/install/controller.js, test/unit/pages/install/controller-test.js
It should suggest a failure just like the failed installation. Hence it should look like a failure, including the new fancy icon and colours.
=> Make failed download progress bar look like a proper failure

browser/directives/componentPanel.html, browser/directives/componentPanel.js, test/ui/confirm-test.js
Items like hyper-v have no use for file sizes, so it feels better not to show them, rather than use 0.00 PB
=> Hide void/zero file sizes

main/menu.js
looks like mac menu does not support entries without submenus, so I added one for Help
=> Fix help menu not appearing on mac

requirements.json
The download size is stored in bytes(binary). Updated the value for the products after checking with the size on disk data after download.
=> Fix download size value for product stored in bytes

requirements.json
because it can't be downloaded
=> Remove dowload size from fuse tools

browser/model/installable-item.js
Fix adds check for downloaded resources based on file size.
SHA256 sum verification is done later during installation.
Checking file size is much faster than calculating SHA256
for every downloaded file.
=> JBDS-4310 Verify what resources is already downloaded

browser/pages/install/controller.js, browser/pages/location/controller.js, browser/pages/selection/controller.js, browser/services/data.js, test/unit/services/data-test.js
target folder, logs and registry items should be created after the point of no return. Moving them from after selection page to the start of the installation.
=> JBDS-4575 Move persistent changes to the start of installation

browser/model/installable-item.js, test/unit/model/cygwin-test.js, test/unit/model/devstudio-test.js, test/unit/model/jbosseap-test.js, test/unit/model/jbossfuse-test.js
Removes waiting for ${name} to finish installation message
from install method, because new implementation install
components one by one.
=> Fix #908 Weird progress status

browser/model/installable-item.js
Check if download cache file doe not exist before
creating it to avoid problems on macOS.
=> Fix #909 Downloaded components posing as not downloaded

browser/pages/install/controller.js, test/unit/pages/install/controller-test.js
Current progress holder is intended to report download progress
only. This commit makes it generic and replaces 'download size'
related names to just 'amount' throughout installation page controller.
=> Replace 'download size' to 'amount' throughout install controller

browser/model/installable-item.js, browser/pages/confirm/confirm.html, requirements.json
Use 'No download required' for components with size equals undefined
or 0.
=> Fix #922 Fuse Tooling appears as 'Selected to download' on conf page

browser/model/cdk.js, browser/services/platform.js, test/unit/model/cdk-test.js, test/unit/services/platform-test.js
Local group names are localized on windows and therefore to support windows installations with different locale CDK installer cannot use 'Hyper-V Administrators' group name when adding current user into it using `net localgroup` command. First it should get localized name by SID (security identifier) for the group using powershell script.
=> Fix #930 Hyper-V Administrators group localization issue

browser/app.css, browser/pages/confirm/confirm.html
Fixes #952.
@dgolovin As macOS had less components when `select All`, so scrolling didn't show up the gap as mentioned in the bug. I have fixed the gap between the breadcrumb and header and verified on macOS. Can you please check if this works on Windows.
=> Fix #952 breadcrumb and component scrolling layout

browser/pages/install/controller.js
Current install page show total download sizw w/o counting
downloaded components
=> Show the same total download size on confirmation and install page

browser/bootstrap.js
Fix #976 
Added the screenshot with the touch bar display for panels in About Dialog.
=> add macOS touchbar for about dialog

browser/bootstrap.js
Fix #981 
- This gives the touch bar feature to goto `Help`, `About`. It provides the version of the application and helps the user directly quit the application.
- This adds feature for _About Dialog_ to close from touch Bar on macOS.
=> add context menu features on macOS touch bar

browser/model/virtualbox.js, test/unit/model/virtualbox-test.js
Extract the certificate from virtualbox executable and import it before installing. In case somebody does not have it yet, it should no longer prompt for "trusting oracle" when installing vbox drivers.
=> Import virtualbox certificate before installation (fix #1013)

test/check-requirements.js
``` shell
-------------------------------
Checking download URLs
jbosseap - url: http://download-node-02.eng.bos.redhat.com/released/JBEAP-7/7.0.0/jboss-eap-7.0.0-installer.jar
jbosseap - size: 184545112B
jbosseap - size: 184545112B in requirements.json
fuseplatformkaraf - url: http://download-node-02.eng.bos.redhat.com/released/JBossFuse/6.3.0/jboss-fuse-karaf-6.3.0.redhat-187.zip
fuseplatformkaraf - size: 785784505B
fuseplatformkaraf - size: 785784505B in requirements.json
cygwin - url: https://cygwin.com/setup-x86_64.exe
cygwin - size: 907795B
cygwin - size: 907795B in requirements.json
cdk - url: http://cdk-builds.usersys.redhat.com/builds/weekly/24-Oct-2017.cdk-3.2.0/windows-amd64/minishift.exe
cdk - size: 487340032B
cdk - size: 487340032B in requirements.json
jdk - url: …
```
=> Fix #935 Add check for actual and declared size for requirements

browser/model/devstudio.js, browser/model/helpers/downloader.js, browser/model/installable-item.js, browser/model/jbossfuse.js, browser/pages/confirm/controller.js, browser/pages/install/controller.js, browser/pages/selection/controller.js, browser/services/data.js, requirements.json, test/unit/model/cdk-test.js, test/unit/model/cygwin-test.js, test/unit/model/devstudio-test.js, test/unit/model/helpers/downloader-test.js, test/unit/model/installable-item-test.js, test/unit/model/jbosseap-test.js, test/unit/model/jbossfuse-test.js, test/unit/model/jbossfusekaraf-test.js, test/unit/model/jdk-install-test.js, test/unit/model/kompose-test.js, test/unit/model/virtualbox-test.js, test/unit/pages/install/controller-test.js, test/unit/services/data-test.js
This turned out way bigger than originally intended (to fix #1012). On the upside, it now fixes #995 as well.
Changelog:
- split checkAndDownload into check and download (if check is successful, download is not even called)
- made all checks done per file for each component
- InstallerDataService takes care of delegating to each component, the install controller now mostly just uses that
- the flow is now 'verify existing => download (and check) => install' using events to advance to next step
- all steps now use the progress bar
- post download checks are now queued asynchronously to the download, and if some remain after download is done, they take over the progress bar
Take it for a spin please, and once again sorry for how big it turned out to be - it just didn't seem to work in …
=> [wip]Queue operations with progress

browser/model/cdk.js, browser/model/cygwin.js, browser/model/helpers/downloader.js, browser/model/hyperv.js, browser/model/installable-item.js, browser/model/jdk-install.js, browser/model/virtualbox.js, browser/pages/selection/controller.js, browser/services/data.js, browser/services/openpgp.js, browser/services/platform.js, test/unit/services/platform-test.js
Form documentation for `Promise.prototype.then(onFullfilled, onRejected)` [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then):
"returns a value, the promise returned by then gets resolved with the returned value as its value;"
=> Remove not required Promise.resolve() throughout the code

uninstaller/uninstall-helper.ps1
This let uninstaller to deal correctly with long file names
=> Add prefix \\?\ for target install folder when removing it in

browser/directives/componentPanel.html
=> Hide the entire detection div when it is not in use

browser/model/installable-item.js
This fix lets to use installable-item.js as module for installers declared in requirements.json. It would just download declared item in cache and installation just calls success method.
=> Allow to use installable-item.js as module in requirements.json

browser/model/che.js, requirements.json, test/check-requirements.js, test/unit/model/che-test.js
=> Fix #911 Add Eclipse Che Installer

requirements.json
This fix includes kompose [1.7.0](https://github.com/kubernetes/kompose/releases/tag/v1.7.0) into installer
=> Update kompose to 1.7.0.TP

requirements.json
Release when https://issues.jboss.org/browse/RHDENG-1892 pushed to production.
=> Use developers portal redirects to download kompose 1.7.0 release

uninstaller/uninstall-helper.ps1
Enforce get-childitem to return an array no matter how many subfolders it finds, so the for loop always iterates over the same type.
=> Fix uninstaller failing on a single subfolder (fix #1232)

gulp-tasks/dist-win32.js, gulpfile.babel.js
Fix allows to run https fake server to minic download manager on macOS and windows.
=> Move prefetch-all task from dist-win.js to gulpfile

README.md, browser/model/helpers/installer.js, browser/model/virtualbox.js, browser/pages/install/install.html, browser/services/platform.js, package-lock.json, package.json, test/unit/model/helpers/installer-test.js, test/unit/model/virtualbox-test.js, test/unit/services/platform-test.js
Use sudo-prompt to get elevated privileges:
- use actual sudo instead of osascript elevation
- customizable auth dialog (name and icon match the product, yay)
- credentials remain active until invalidated (session runs out / sudo -k)
- unless tty-tickets is enabled, only one dialog will be presented during the installation
=> Replace osascript with sudo prompt

browser/model/cdk.js, browser/services/platform.js, test/unit/model/cdk-test.js, test/unit/services/platform-test.js, uninstaller/uninstall-helper.ps1
Since we default to installing into program files, it seemed logical to add items to the system (machine) path rather than the user one. Things like oc still remain on user path since it is installed in user's home.
=> Use machine path rather than user path on windows

browser/model/helpers/downloader.js, browser/model/installable-item.js, browser/services/request.js, gulpfile.babel.js
so that the http requests for testing purposes can be filtered out in the statistics.
Feel free to edit the agent string itself if you don't like it :)
=> Use a different user-agent header for debug/test runs (#fix 1269)

browser/pages/selection/controller.js, browser/services/componentLoader.js, requirements.json, test/unit/pages/selection/controller-test.js, test/unit/services/componentLoader-test.js
This fix gets read of installAfter hell in requirements.json. It flatten graph or components and then just set installAfter in simple cycle. Net step would be getting rid of installAfter notion. Installation would just go in cycle for flatten requirements graph.
=> Simplify installation ordering

browser/model/helpers/installer.js, browser/services/platform.js, gulpfile.babel.js, test/unit/model/helpers/installer-test.js, test/unit/services/platform-test.js
it turns out the icons needed by sudo prompt on mac were not packaged into the final archive and caused the prompt to fail miserably
=> Package icons into the final archive

browser/model/installable-item.js, package-lock.json, test/unit/model/installable-item-test.js
Remove not needed code from install item install method.
Installation order now is based on flatten dependencies graph so
there is no reason to check if required components installed,
because required components are installed first.
=> Clean up install method

requirements.json, test/check-requirements.js
7zip is no longer hosting the files, everything is now on sourceforge. Trying to access the files directly instead of the redirect. Hopefully requirement check will be able to crunch it once more.
=> Use 'direct' link to 7zip

README.md, gulp-tasks/dist-darwin.js, gulp-tasks/tests.js, protractor-conf.js
=> Change packaging for macOS to DMG

browser/pages/start/controller.js
As there is no update on the redesign timeframe, the permanent links for hello-world are not yet updated. So rolling back to the url which won't break in the future till the new design is up.
Relates to  #1132
=> update cdk hello-world page without hash link

browser/directives/componentPanel.html, browser/model/jdk-install.js, browser/model/virtualbox.js, test/unit/model/jdk-install-test.js
Fix #1336 and at least show message that Java 1.8.0 is required.
=> Allow Java 9+ to be detected

browser/model/jdk-install.js, browser/pages/selection/controller.js
requires https://github.com/redhat-developer-tooling/developer-platform-install/pull/1384 and https://github.com/redhat-developer-tooling/developer-platform-install/pull/1385 to work.
=> Select Open JDK 8 to install if required and Java 9+ detected

browser/pages/selection/controller.js
Turns out one can select a component with its dependencies in one channel, then switch to a different channel and use 'clear all' to simply deselect the dependencies without the original item. 
Example: select Java Development in Guided Development channel -> go to Java Development channel -> click Clear All -> everything in Java Dev channel gets deselected even though Guided Development is still selected
This PR should check if the deselected component still has something depending on it before committing.
=> Fix 'clear all' deselecting components while dependents are still selected

browser/services/platform.js
when run from dmg, the installer has its PATH limited to `/usr/bin:/bin:/usr/sbin:/sbin`
no idea why, but since xhyve is usually in `/usr/local/bin` we should look there as well
=> Look for xhyve in /usr/local/bin
