redhat-developer-tooling/developer-platform-install

- browser/main.js
- browser/model/cdk.js
- browser/model/virtualbox.js
- browser/pages/install/controller.js
- browser/services/data.js
- main/index.es6.js
This fix:
- adds new event for ipcReenderer fo inform about finishing all downloads
- removes this.$scope.$apply form ProgressState class to adress
https://docs.angularjs.org/error/$rootScope/inprog
- makes virtualbox to wait notification about finishing all downloads
> DEVEX-93 virtualbox nstallation interrupts ongoing downloads

- package.json
Denis, Joshua, Jan, no action is required from your side, just testing Jenkins PR plugin.
> fs-extra, glob and yargs upgraded

- browser/pages/account/controller.js
None pretty solution v.2 to fix the tests and app at the same time.
> JBDS-3682 Online installer reports missing package.js file

- browser/model/cdk.js
> JBDS-3656 The installer should use Vagrantfile provided by CDK.

- browser/model/helpers/installer.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
- test/unit/model/jbds-test.js
This fix adds required argument and redirects JBDS output
to installation.log file
> JBDS-3693 JBDS instal should be running with -DTRACE=true

- browser/app.css
- browser/pages/account/account.html
- browser/pages/account/controller.js
There are no functional changes. 
Unit tests passed.
> Update the Login page UI

- browser/app.css
- browser/directives/progressBar.js
- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/install/controller.js
- browser/pages/install/install.html
While not complete this UI update brings it more in line with the design. It also changes the Directive for the Progress Bar to support more fields.
> JBDS-3607 - Update to the Install page. 

- browser/app.css
- browser/main.js
- browser/pages/account/controller.js
- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
- browser/pages/location/controller.js
- browser/pages/location/location.html
- browser/services/data.js
- test/browser/breadcrumb-test.js
- test/unit/pages/account/controller-test.js
- test/unit/services/data-test.js
New page created for selecting target location to install
> JBDS-3771 Create new page for selecting target location in installer

- browser/app.css
- browser/main.js
- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
- browser/pages/location/location.html
This touches all the models but that is only to handle the click event and change the arrow.
> JBDS-3607 - Change Confirmation page checkbox to an arrow 

- browser/model/helpers/version.js
- browser/model/virtualbox.js
- package.json
- test/unit/model/helpers/version-test.js
Fix contains:
- Version class wrapper around semver
- Version class tests
- Simple update for virtualbox installer to use Version class
> JBDS-3749 Add Version class based on semver module

- gulpfile.js
- package.json
- requirements.json
JBDS-3778 2 methods: getSHA256(filename) & createSHA256File(filename)
> JBDS-3778 2 methods: getSHA256(filename) & createSHA256File(filename)

- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
> JBDS-3714 - Add UI for back and cancel button to the Confirm page. 

- browser/app.css
- browser/pages/confirm/confirm.html
- browser/pages/location/controller.js
- browser/pages/location/location.html
The backend still needs to be worked out.
> JBDS-3607 - Update the UI for the Location folder page. 

- browser/app.css
- browser/main.js
Trim the Breadcrumbs at the top, to remove the Login / Account reference.
> JBDS-3607 - Trim the Breadcrumbs at the top

- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/confirm/confirm.html
- browser/pages/install/controller.js
First iteration of binding to new UI
> JBDS-3720 Bind the logic to the new UI

- browser/pages/location/controller.js
Fix saves location when Back button pressed
> JBDS-3818 Installer does not remember selected location

- gulpfile.js
- requirements.json
implement remote SHA256sum check (JBDS-3859)
> implement remote SHA256sum check (JBDS-3859)

- browser/model/helpers/downloader.js
- browser/model/helpers/util.js
- test/unit/model/helpers/downloader-test.js
- test/unit/model/helpers/hash-test.js
- test/unit/model/helpers/installer-test.js
- test/unit/model/helpers/util-test.js
Improving test coverage, starting with helper classes. More to come.
> Unit tests for helper classes

- test/unit/model/cygwin-test.js
- test/unit/model/helpers/downloader-test.js
- test/unit/model/helpers/hash-test.js
- test/unit/model/virtualbox-test.js
Apparently some tests have been throwing errors that did not get caught or even logged for that matter. This PR fixes those errors.
> Fix some masked uncaught errors in tests

- browser/main.js
- browser/model/cdk.js
- requirements.json
- test/unit/model/cdk-test.js
Fix removes pscp.exe everywhere:
1. requirements.json
2. cdk installer
3. unit tests
> JBDS-3886 Remove pscp.exe from platform-installer

- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/helpers/downloader.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/install/controller.js
- browser/pages/install/install.html
- test/unit/model/cdk-test.js
- test/unit/model/helpers/downloader-test.js
Fix enables:
- downloader to save failed downloads
- instll step restart download from dialog
> JBDS-3666 Back off and retry if download fails

- browser/model/helpers/downloader.js
> JBDS-3835 Back of and retray if download fails

- browser/model/jbds-autoinstall.js
- browser/model/jbds.js
Simple fix with hardcoded version 10.0.0 to replace https://github.com/redhat-developer-tooling/developer-platform-install/pull/165
> JBDS-3878 pull installer version from package.json

- browser/app.css
- browser/model/cdk.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
- browser/pages/install/controller.js
- browser/pages/install/install.html
- browser/pages/start/start.html
- test/unit/model/cdk-test.js
Fix enables optional installation for all components form stack.
> JBDS-3787 Installer - Installation of each component should be optional

- browser/model/cdk.js
Fix updated vagrant service manager plugin file name
> Fix CDK installation problem for version built Jun 3rd

- requirements.json
bump up to latest cdk RC5 from 20160616
> bump up to latest cdk RC5 from 20160616

- test/ui/breadcrumbs-base.js
- test/ui/location-test.js
- test/ui/login-test.js
First step in removing karma based tests - adding the checks to current ui tests. Tests for remaining pages coming soon.
> Add breadcrumb checks to ui tests

- browser/main.js
- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/helpers/util.js
- browser/model/installable-item.js
- browser/model/jbds-autoinstall.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/account/controller.js
- browser/pages/confirm/confirm.html
- test/unit/model/cdk-test.js
- test/unit/model/jbds-test.js
Attempt to get all the names, versions and description from requirements.json instead of hardcoded strings in code.
> Get installables info from requirements.json

- browser/model/cdk.js
- test/unit/model/cdk-test.js
Fix PATH variable name on windows, path => Path.
> JBDS-3961 CDK installation failed with progress bar stuck in 99%

- browser/directives/pathValidator.js
- browser/main.js
- browser/pages/location/location.html
- browser/pages/location/messages.html
- package.json
- test/ui/location-test.js
Refactor validation for Installation folder and add drive validation. Implementation based on angular-messages. Protractor tests updated to test new validator for drive in selected path.
> JBDS-3817 Folder validation does not check if the selected drive exists

- browser/pages/account/controller.js
- test/unit/pages/account/controller-test.js
configure response type as text
> JBDS-3624 Error while parsing response from auth server

- browser/pages/confirm/confirm.html
- browser/pages/location/location.html
- browser/pages/start/controller.js
- main/index.js
Fix adds overall close message handler for all pages except last one.
> JBDS-3713 Add a prompt when exiting the installer (i.e. via the cross button)

- browser/model/helpers/downloader.js
- test/unit/model/helpers/downloader-test.js
set the same user-agent as in electron session
> JBDS-3979 Set user agent for http requests from DevSuite Installer

- gulpfile.js
Fix downloading issues:
- requirements always downloaded;
- sha256 is not checked after download;
- no logging in download related tasks..
> JBDS-3991 create build folder with timestamp

- requirements.json
Virus check reports added for files less than 125Mb.
> Virus check reports added to requirements.json

- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/jbds.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
Fix updates condition for install method to avoid the problem.
> JBDS-4024 Components installation sometimes called twice

- browser/pages/confirm/confirm.html
Fix updates error message to take lowest supportet version from
virtualbox installer.
> JBDS-4030 Can't use vagrant 1.7.4 with installer

- browser/model/helpers/downloader.js
- browser/model/helpers/hash.js
- test/unit/model/helpers/hash-test.js
Fix changes event listeners to 'close' and that fixes the issue.
> JBDS-4041 cygwin installer fails to start with EBUSY error in install.log

- browser/services/logger.js
- test/unit/services/logger-test.js
This fix contains tests for Logger class to increase unit tests code coverage
> Tests for Logger class

- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- test/unit/model/cdk-test.js
- test/unit/model/cygwin-test.js
- test/unit/model/jbds-test.js
- test/unit/model/jdk-install-test.js
- test/unit/model/vagrant-test.js
- test/unit/model/virtualbox-test.js
- add missing callbacks and unified the rest
- tweak ipcRenderer handling, so it can be mocked in tests
> JBDS-4082 fix unhandled promise rejection in unit tests

- browser/model/cdk.js
- browser/model/helpers/installer.js
Fix changes the logging to Path environment variable only
> JBDS-4072 Log only relevant environment variables not all of them

- browser/services/data.js
Log 'Setup done' only for selected for installation components.
> JBDS-4037 Log contains 'setup finished' entries for skipped components

- uninstaller/uninstall.ps1
Make uninstaller remove desktop and start shortcuts for devstudio.
> JBDS-4111 Add shortcuts cleanup to uninstaller

- gulp-tasks/common.js
- gulp-tasks/download.js
- gulpfile.js
Fix moves out functions to different files to be able to share them
between different guil related files.
> JBDS-3875 Split gulpfile.js to multiple modules to simplify maintenance

- browser/pages/confirm/controller.js
Fix removes confCtrl from gloabal scope and updates all references to this
> Remove confCtrl from global scope in confirmation page controller

- browser/model/cygwin.js
- browser/pages/confirm/confirm.html
Fix hides cygwin form installer on Mac
> JBDS-4114 Remove Cygwin form Mac Installer

- README.md
- gulp-tasks/tests.js
- gulpfile.js
- protractor-conf.js
- test/system/default-test.js
- test/system/windows/downloadInstaller.ps1
- test/system/windows/runTests.ps1
A few updates and some scripts to run end to end tests on ci (windows only so far).
> End-to-end test runnable on windows ci

- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- test/system/windows/npm-debug.log
- test/unit/model/jbds-test.js
- test/unit/model/jdk-install-test.js
- test/unit/pages/install/controller-test.js
Fix makes key() method looks more like static constant
> Rename InstallableItem.key() static metod to get KEY()

- browser/model/jdk-install.js
- test/unit/model/jdk-install-test.js
Fix adds tests for java detection method to increase code coverage for unit tests
> Unit tests for java detection

- browser/model/jdk-install.js
Fix removes new operator from default callback value.
> Fix callback parameter default value

- test/unit/model/jdk-install-test.js
Fix adds missing tests to increase coverage to 100%
> Increase unit-tests coverage for JdkInstall to 100%

- browser/model/installable-item.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/confirm/controller.js
Fix adds:
* default implementation for validateVersion method
* change var declaration to let in cycle to def validation callbacks
* add check for selected option to be present
> JBDS-4163 undefined have no valid property exception

- browser/pages/account/controller.js
So it actually gets you to registration instead of login
> JBDS-4028 Use direct link to registration form

- browser/model/cygwin.js
Fix splits where output and use first line as detected location
> JBDS-4166 Cygwin detection configures wrong location

- browser/app.css
- browser/model/cygwin.js
- browser/model/installable-item.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
- test/unit/model/jdk-install-test.js
Fix adds macOS specific features for vagrant/virtualbox/jvm:
1. detection
2. validation
3. error messages
> JBDS-3975 Support for platform specific installations

- browser/model/jdk-install.js
- requirements-linux.json
Fix parce major, minor and pathc versions from full version to
use with semver module instead of full version with underscore
> JBDS-4165 Version parsing error

- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/installable-item.js
- browser/model/jbds.js
- browser/model/jdk-install.js
- browser/model/vagrant.js
- browser/model/virtualbox.js
- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
- requirements-darwin.json
- test/unit/model/cdk-test.js
- test/unit/model/cygwin-test.js
- test/unit/model/jbds-test.js
- test/unit/model/vagrant-test.js
Prep refactoring to allow different install methods per platform
> JBDS-4174 Install vagrant/virtualbox on macos

- browser/model/jdk-install.js
- test/unit/model/jdk-install-test.js
Fix adds platform specific tests to JDK unit tests
> Improve code coverage for JDK Installer

- requirements-darwin.json
- requirements-win32.json
Fix typo in DM manager URL for devstudio.
> JBDS-4125 Provide environment variable to override developers.redhat.com

- package.json
See manually imported results in https://codecov.io/gh/redhat-developer-tooling/developer-platform-install. I will update Jenkins jobs after this PR is merged, otherwise it would cause them to fail (non-existing npm script).
> Codecov dependency and script added

- gulp-tasks/download.js
So we don't get NaNNaNNaNNaNNaNNaNNaNNaNNaN Batman!
instead of the percentage
> Rename percentage to percent for request-progress 3.0

- test/unit/model/cygwin-test.js
Fix adds test for cygwin detection
> Increase cygwin installer unit tests coverage

- README.md
Added the configuration for linux in README.md
> Added configuration for linux in README.md

- browser/services/data.js
- test/unit/services/data-test.js
Remove windows uninstaller from mac distribution
> JBDS-4170 Remove windows uninstaller from mac distribution

- requirements-win32.json
Since the file has changed and build are failing...
> Update cygwin to 2.6.1

- browser/services/platform.js
Fix adds stubbed method that returns promise resolved to false,
implementation for windows is expected to come first.
> JBDS-4010 DevSuite installer should check if virtualization enabled

- test/system/test-base.js
- test/system/windows/installComponents.ps1
- test/system/windows/runTests.ps1
enforce the execution order + code error fixes
> Fix system tests against invalid component versions

- test/unit/model/installable-item-test.js
Increase unit tests code coverage installable item
> Increase unit tests code coverage installable item

- test/unit/model/helpers/downloader-test.js
Increase unit tests code coverage for downloader test
> Increase unit tests code coverage for downloader test

- .eslintrc.js
- browser/main.js
- browser/pages/confirm/controller.js
- package.json
- test/.eslintrc.js
- test/angular-test-helper.js
- test/unit/pages/confirm/controller-test.js
- test/unit/pages/location/controller-test.js
- test/unit/pages/start/controller-test.js
Fix:
1. Cleanup eslint fiolations
2. Adds angular test helper to allow run tests for controllers with
ngMock
3. Adds test for browser/pages/confirm/controller.js
> Tests code update

- browser/services/platform.js
- test/unit/services/platform-test.js
DevSuite installer should check if virtualization extension is enabled
> JBDS-4010 DevSuite installer should check if virtualization extension is enabled (win32)

- browser/services/platform.js
- test/unit/services/platform-test.js
JBDS-3869 DevSuite Installer should check/warn if Hyper-V is already enabled (win32)
> JBDS-3869 DevSuite Installer should check/warn if Hyper-V is already enabled (win32)

- browser/model/cdk.js
- browser/model/installable-item.js
- test/unit/services/platform-test.js
Fix resolves cdk install issue and resolves eslint violations
> CDK install never finishes installation

- README.md
- package.json
- test/unit/model/jbds-test.js
Fix adds node module which does the job and script to do
dependencies upgrade and npm update in one command.
> Script to update declared dependencies to latest version

- browser/pages/account/account.html
- browser/pages/account/controller.js
Fix:
- moves validation logic to controller;
- adds reset for error reported after submit if any field is edited;
- elements location within page, so nothing moves after error appears.
> JBDS-4066 Improve error reporting on account info page

- browser/model/cdk.js
- browser/services/platform.js
- requirements-darwin.json
- requirements-linux.json
- requirements-win32.json
- test/unit/model/cdk-test.js
- test/unit/services/platform-test.js
Fix adds --force option to minishift setup-cdk and fixes other
installation issues.
> JBDS-4246 Implement minishift cdk-setup in devsuite installer

- browser/main.js
- browser/model/cdk.js
- browser/model/cygwin.js
- browser/model/devstudio.js
- browser/model/installable-item.js
- browser/model/jdk-install.js
- browser/model/virtualbox.js
- test/unit/model/cdk-test.js
- test/unit/model/cygwin-test.js
- test/unit/model/installable-item-test.js
- test/unit/model/jbds-test.js
- test/unit/model/virtualbox-test.js
- test/unit/pages/location/controller-test.js
- test/unit/services/data-test.js
it was never really being used
> Remove installTime from installable-item

- browser/directives/pathValidator.js
- browser/pages/location/messages.html
- test/ui/location-test.js
characters are present in folder name
> JBDS-3825 Cygwin installs into a different folder when some non-ascii  characters are present in folder name

- browser/model/cygwin.js
- test/unit/model/cygwin-test.js
This PR has a fix to suppress sygwin installer window, when installer runs in automated mode.
> JBDS-4308 Run cygwin with hidden window as powershell start-process

- browser/pages/start/controller.js
- test/unit/pages/start/controller-test.js
This fix adds test for launching devstudio on windows
> Increase start controller unit test coverage

- test/unit/directives/breadcrumb-test.js
- test/unit/directives/path-validator-test.js
- test/unit/directives/progressbar-test.js
- test/unit/model/installable-item-test.js
- test/unit/pages/install/controller-test.js
- test/unit/pages/start/controller-test.js
sinon is not updated to 2.0.0 yet, because of migration problems with unit tests
> Clean up eslint rule violations

- browser/model/hyperv.js
- browser/model/installable-item.js
Let components be accepted when not selected or detected on other platforms, also skip hyperv outside windows.
> JBDS-4316 Fix confirm page checkboxes outside windows

- browser/model/hyperv.js
- test/unit/model/hyperv-test.js
Fix set selectedOption as detected, which works as skip swithc
when there is no detected option in option collection.
> JBDS-4314 Hyper-v shows up on Install page on macOS

- browser/model/devstudio.js
Fix removes unused code to increase code coverage. This commit is
going to be recorded in JIRA to let for easy revert when removed
code is acually used
> JBDS-4327 DevStudio detection

- test/system/test-base.js
Round two, because doing it in one go is too hard.
> Fix requires in e2e test base

- browser/model/kompose.js
- package.json
- test/unit/model/kompose-test.js
hijacked #666 for some more fixes, hopefully the job turns green now
> Kompose Test fixes

- .gitignore
- gulp-tasks/tests.js
- gulpfile.js
- protractor-conf.js
- test/screenshotReporter.js
Any time a protractor based spec fails, it should capture a screenshot with the spec description.
> Capture screenshot on UI test failure

- browser/model/jdk-install.js
- test/unit/model/helpers/downloader-test.js
Fix changes regex to accept version without _
> Detection never ends on macos

- browser/app.css
- browser/pages/confirm/confirm.html
- browser/pages/install/install.html
- test/ui/confirm-test.js
> JBDS-4328 Move 'Detection is in progress' indicator in the middle

- gulp-tasks/dist-darwin.js
> Remove Alpha qualifier from mac

- devstudio.manifest
- gulp-tasks/dist-win32.js
Fix adds application manifest file and rcedit application-manifest
attribute when bulding self extracting archive.
> JBDS-3822 Fix "This program might not have installed correctly"

- browser/model/devstudio.js
- browser/model/jbosseap-autoinstall.js
- browser/model/jbosseap.js
- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
- browser/services/componentLoader.js
- browser/services/data.js
- browser/services/platform.js
- requirements.json
- test/check-requirements.js
- test/ui/confirm-test.js
- test/unit/model/jbosseap-test.js
- test/unit/pages/confirm/controller-test.js
- test/unit/services/data-test.js
This PR replaces https://github.com/redhat-developer-tooling/developer-platform-install/pull/717
> JBDS-4399 Include latest JBoss EAP available from developers.redhat.com

- browser/model/installable-item.js
- config-bundle.txt
- config.txt
- gulp-tasks/config.js
- gulp-tasks/dist-win32.js
- gulpfile.js
- main/index.js
Result is new bundled installer starts 3 times faster than old one, but it is 70Mb bigger.
> JBDS-3716 Improve all in one installer performance

- test/ui/confirm-test.js
- test/ui/install-test.js
instead of them being hardcoded
> Make UI tests load all requirements automatically

- browser/model/jdk-install.js
- test/unit/model/jdk-install-test.js
Fix adjusts detection for java installation on macOS so it
does not affect detection for windows
> Java detection for windows is broken

- browser/services/platform.js
- test/unit/services/platform-test.js
Merge with resolved conflicts for https://github.com/redhat-developer-tooling/developer-platform-install/pull/741
> JBDS-4438 Detect free space available on disk for Windows

- browser/app.css
- browser/model/jbossfusekaraf.js
- browser/pages/confirm/confirm.html
- browser/pages/confirm/controller.js
- browser/services/data.js
- package.json
- requirements.json
- test/check-requirements.js
- test/unit/model/fuseplatformkaraf-test.js
> JBDS-4457 Include Fuse Platform on Apache Karaf into DevSuite Installer

- browser/pages/account/account.html
- browser/pages/account/controller.js
- browser/services/data.js
- test/mock/electron.js
- test/unit/pages/account/controller-test.js
Fix adds package.json data to data serrvice and use version
attribute when adds devsuite registry enrty.
> JBDS-4460 Devsuite registry entry has hardcoded version to 1.4.0

- gulpfile.js
- requirements.json
> Update devstudio to GA

- browser/model/jbossfuse.js
Fix set default password to changeit1 to comply with
password validation rules
> JBDS-4459 Fuse runtime installation failure on macOS

- requirements.json
Fix update fuse platform names to match names from developers portal
> Update Fuse Product name and descriptions

- browser/model/installable-item.js
- browser/services/data.js
- test/unit/model/cdk-test.js
- test/unit/model/cygwin-test.js
- test/unit/model/devstudio-test.js
- test/unit/model/jbosseap-test.js
- test/unit/model/jbossfuse-test.js
- test/unit/model/jdk-install-test.js
- test/unit/model/kompose-test.js
- test/unit/model/virtualbox-test.js
- test/unit/services/data-test.js
Fix moves cache location to %APPDDATA%\..\local\RedHat\DevSuite\cache
on windows and ~/Library/Application Support/RedHat/DevSuite/cache on
macOS
> JBDS-4462 Change cache location

- browser/model/virtualbox.js
a silly fix for a serious issue
> JBDS-4500 Fix virtualbox on mac and spaces in path

- package.json
This reverts commit d4d351c4d5936b0f2988a24af0cbf8d31a2d4728.
> Revert "Remove openpgp module"

- browser/app.css
- browser/directives/componentPanel.html
- browser/model/installable-item.js
- requirements.json
- test/ui/confirm-test.js
https://issues.jboss.org/browse/JBDS-4410
Added the download size information with the version name. Mockup is attached to the jira.
> JBDS-4410 Add download size for packages

- browser/app.css
- browser/pages/confirm/confirm.html
- browser/pages/location/location.html
https://issues.jboss.org/browse/JBDS-4510
Fix spinner css and the breadcrumbs alignment.
@dgolovin Please review
> Fix css issues and spinner alignment

- README.md
This fixes the latest nvm version for macOS installation.
> NVM version fix for macOS installation

- browser/app.css
- browser/directives/progressBar.html
- test/ui/install-test.js
Added status of the progress for different product components.
Display failed progress bar.
https://issues.jboss.org/browse/JBDS-3839
https://issues.jboss.org/browse/JBDS-4519
> Progress panel failed message and download/Installation status

- browser/app.css
- browser/directives/breadcrumbs.html
- browser/directives/progressBar.html
- browser/pages/account/account.html
- browser/pages/confirm/confirm.html
- browser/pages/install/install.html
- browser/pages/location/location.html
- browser/pages/start/start.html
Fixes https://issues.jboss.org/browse/JBDS-4069
> JBDS-4069: Fix breadcrumbs header

- requirements.json
> [2.0.1] Update cygwin version

- browser/pages/confirm/confirm.html
> JBDS-4411 Update label for required disk space

- browser/pages/location/controller.js
- browser/pages/location/location.html
- browser/services/data.js
so it doesn't just stay empty complaining about stuff
> JBDS-4573 Fill in default folder when empty target input loses focus

- browser/app.css
- browser/pages/selection/controller.js
- browser/pages/selection/selection.html
- test/unit/pages/selection/controller-test.js
#920 
- https://issues.jboss.org/browse/JBDS-4554
- This is made as per the Mockup 1 provided by crobson.  https://issues.jboss.org/secure/attachment/12425983/Selectall-Option1.png
> replace context menu select all/deselect all with ui element

- browser/app.css
- browser/directives/progressBar.html
- browser/pages/install/controller.js
- browser/pages/install/install.html
- browser/pages/selection/selection.html
This will open the default editor based on the OS Platform to display the log file.
> Fix #915 show ui control to display failure log

- requirements.json
> Replace kompose 1.3.0 link to redirect on developers.redhat.com #941

- browser/directives/pathValidator.js
- browser/pages/location/messages.html
- browser/services/data.js
- test/ui/location-test.js
- test/unit/services/data-test.js
> JBDS-4333 Install DevSuite into 'c:\Program Files\DevelopmentSuite' by default

- browser/model/cdk.js
- browser/model/jdk-install.js
- test/unit/model/cdk-test.js
> Fix installation into location with space for CDK and OpenJDK 

- browser/pages/install/install.html
Used patternfly alert class. http://www.patternfly.org/pattern-library/widgets/#alerts
> updated alert with patternfly alert for download error modal

- browser/directives/progressBar.html
- browser/model/helpers/installer.js
- browser/pages/install/controller.js
- browser/services/data.js
- test/mock/electron.js
- test/unit/model/helpers/installer-test.js
- test/unit/pages/install/controller-test.js
- test/unit/services/data-test.js
> Fix #916 Show installation progress based on number of selected components

- browser/pages/confirm/confirm.html
> Fix #966 update icon for No download components

- uninstaller/uninstall-helper.ps1
- uninstaller/uninstall.ps1
timestamp was missing, putting it back
> Fix uninstall error when removing registry entry

- browser/pages/start/controller.js
- test/unit/pages/start/controller-test.js
hopefully the last of the space problems :/
> Open devstudio on mac even with spaces

- README.md
> update Readme for node/nvm version bump

- gulpfile.babel.js
- package.json
This fix is for the case when some files are removed,
to avoid running app with deleted files preserved in
transpiled folder
> Remove transpiled folder before running transpiler again

- browser/services/data.js
- gulp-tasks/dist-win32.js
- gulp-tasks/download.js
- gulp-tasks/https-server.js
Fix to help with testing of https://github.com/redhat-developer-tooling/developer-platform-install/pull/1072. Prefetch-all is required to work to allow running local https server.
> Fix prefetch-all task to work with new requirements.json structure

- test/unit/model/installable-item-test.js
Some tests I forgot to commit yesterday :)
> Add missing tests

- browser/about.html
- browser/app.css
- browser/index.html
- browser/pages/about/about.html
- browser/pages/about/controller.js
- browser/pages/welcome/welcome.html
- test/system/pages/about-test.js
- test/ui/about-test.js
> Remove unwanted css and add note for close window on macOS

- browser/model/devstudio.js
- browser/model/installable-item.js
- browser/model/jbossfuse.js
- browser/pages/install/controller.js
- browser/services/data.js
- package.json
- test/check-requirements.js
- test/unit/directives/path-validator-test.js
- test/unit/directives/progressbar-test.js
- test/unit/model/cdk-test.js
- test/unit/model/devstudio-test.js
- test/unit/model/helpers/downloader-test.js
- test/unit/model/helpers/installer-test.js
- test/unit/model/helpers/util-test.js
- test/unit/model/jbosseap-test.js
- test/unit/model/jdk-install-test.js
- test/unit/model/virtualbox-test.js
- test/unit/pages/about/controller-test.js
- test/unit/pages/install/controller-test.js
- test/unit/pages/welcome/controller-test.js
- test/unit/services/credentialManager-test.js
- test/unit/services/logger-test.js
- test/unit/services/openpgp-test.js
- test/unit/services/platform-test.js
'useDownload' originally means 'No download required' because this installer has no files to download.
> Fix usage of 'useDownload' attribute

- browser/directives/componentPanel.html
Fix #1066 with one line change.
> Selection for component on click anywhere inside card

- browser/directives/componentPanel.html
> Disable mouse event for checkboxes on selection page

- test/unit/model/helpers/downloader-test.js
otherwise they create some unwanted files
> Mock fs for downloader tests

- gulp-tasks/common.js
- gulp-tasks/download.js
> Fix hasha promise chain in build tasks

- browser/model/devstudio-p2.js
- channels.json
- requirements.json
- test/unit/model/devstudiop2-test.js
> Developer Studio Red Hat Central Installer

- browser/model/cdk.js
- test/unit/model/cdk-test.js
> Move virtualbox path segment after cdk and cygwin

- browser/pages/account/controller.js
Removing == true out of conditions
> Account controller code cleanup

- browser/pages/confirm/controller.js
Fix replaces inner functions with class functions + binding
> Confirmation page controller refactoring

- browser/app.css
- browser/directives/componentPanel.html
- browser/pages/selection/selection.html
- package-lock.json
> Improve channel UI css

- requirements.json
> Fix typo in BPM name

- browser/app.css
- browser/pages/selection/controller.js
- browser/pages/selection/selection.html
- channels.json
- channels description updated
- UI for description, component count, selection count
> UI for channels descriptions and selection status

- test/system/pages/select-test.js
- test/system/windows/installComponents.ps1
- test/system/windows/runTests.ps1
a few wrinkles to iron out when running these tests on CI
> Fix up system test issues

- requirements.json
- test/ui/confirm-test.js
> Fix #1093 Update CDK Description and add additional info

- browser/app.css
- browser/pages/welcome/controller.js
- browser/pages/welcome/welcome.html
- test/unit/pages/welcome/controller-test.js
Initial state for Welcome page
If no newer version is available
If version is up to date
> Fix #1043 Check for DevSuite Installer Updates

- browser/app.css
- browser/pages/selection/controller.js
- browser/pages/selection/selection.html
- channels.json
> move All Components tab in Channels as default in selection page

- browser/model/cdk.js
- test/unit/model/cdk-test.js
group
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> JBDS-4672 - Support spaces in username for Windows to set Hyper-V admin

- browser/model/cdk.js
- test/unit/model/cdk-test.js
- test/unit/pages/welcome/controller-test.js
set up a virtual switch along with the HYPERV_VIRTUAL_SWITCH variable for cdk so the user doesn't need to do it themselves
> Create a virtual switch for cdk on hyper-v (fix #1242)

- browser/services/request.js
- test/unit/services/request-test.js
This fix allows to filer devsuite installer requests to download manager rest interface from requests from browser or other services
> Set user agent string for request module

- browser/model/hyperv.js
- browser/model/jdk-install.js
- browser/pages/selection/controller.js
- browser/services/platform.js
- test/unit/model/hyperv-test.js
- test/unit/model/jdk-install-test.js
- test/unit/services/platform-test.js
I've been messing around with the detection scripts for hypervisors and a bit for java as well. I've found some alternative ways to detect stuff, which seem to be really fast.
Could you guys try this out and tell me if it works for you, and if so how fast it is? (each component reports the time it took to detect in milliseconds into console)
If all goes well, this might turn into a proper PR :)
> Reworked detection for more speed

- browser/directives/pathValidator.js
- browser/model/jdk-install.js
don't allow brackets (they confuse powershell) and remove some jdk issue with carets
> Fix installation failures with special characters in path (fix #1129)

- requirements.json
cygwin setup seems to be getting updates every other day now
> Update cygwin setup sums (again)

- browser/model/guided-dev.js
- browser/model/helpers/util.js
- test/unit/model/guided-dev-test.js
with single cheatsheet entry per selected component
> Guided development composite cheatsheet generation

- browser/directives/componentPanel.html
- browser/model/cdk.js
- browser/model/virtualbox.js
- browser/model/xhyve.js
- browser/services/platform.js
- requirements.json
- test/unit/model/xhyve-test.js
- test/unit/services/platform-test.js
> Add xhyve component for macOS #1267

- browser/model/xhyve.js
- browser/services/platform.js
- test/unit/model/xhyve-test.js
- test/unit/services/platform-test.js
> Fix Xhyve re-detection on window focused event

- browser/model/guided-dev.js
- browser/model/installable-item.js
- test/unit/model/devstudio-test.js
- test/unit/model/jbosseap-test.js
Support for cheatsheet reference list declaration in requirements.json:
``` json
"ref" : {
"camel-project" : {
"id": "org.fusesource.ide.cheatsheets.createCamelProject",
"taskName": "Create a Fuse Integration Project",
"intro": "This cheat sheet walks you through the steps to create a new <b>Fuse Integration</b> project using the Content-Based Router pattern.",
"onCompletion": "Congratulation! You have learned how to Fuse Integration Project!"
}
}
```
> Guided Development support for cheatsheet refs by id

- test/ui/selection-test.js
Test detects if xhyve component is detected and skip virtual box component verification.
> Fix ui-tests on macOS when xhyve is installed

- requirements.json
> Fix provides Guided Development for Fuse in Red Hat Developer Studio

- browser/model/virtualbox.js
- browser/pages/confirm/controller.js
- browser/pages/selection/controller.js
Since we have the isSkipped method I figured we could start using it. It should be a more general solution to the hypervisor choice problem.
Also make sure virtualbox is skipped when xhyve is found.
> Enable conditional skipping of components

- requirements.json
Fix adds new item to Guided Development and Java Development channels,
changes provider for Eclipse Plugin Guided Development to "Eclipse Foundation".
> Java Guided Development component

- browser/pages/start/controller.js
- package-lock.json
This is in context with the url for CDK Getting Started Button. Based on the discussion at https://github.com/redhat-developer-tooling/developer-platform-install/issues/1132#issuecomment-378218980 , the url is updated.
> update CDK get started url

- browser/app.css
- browser/directives/getStarted.html
- browser/directives/getStarted.js
- test/unit/directives/get-started-test.js
> Display dependency components list for selected products installed

- cheatsheets/cdk-creating-project-gd.xml
- requirements.json
This fix uses Guided Development Installer and provides:
1. cheatsheet for 'OpenShift Guided Development'
2. configuration for guided development installer.
> Guided development for CDK

- browser/app.css
- browser/pages/start/start.html
- test/ui/start-test.js
> Add close button to final page

- browser/pages/start/controller.js
- browser/pages/start/start.html
This will add third card component apart from DevStudio and CDK. It will be without Get Started/Docs/Learn links as of now.
Fix #1340
> Add Miscellaneous components card on Final Page

- browser/model/virtualbox.js
- test/unit/model/virtualbox-test.js
there seems to be a little gap when the installer shows "complete" when virtualbox is installing
> Set progress to installing at the start of vbox installation

- requirements.json
Also see https://issues.jboss.org/browse/RHDENG-2022
> Update virtualbox direct links to developers.redhat.com redirects [fix #1314]

- requirements.json
> Replace 'Red Hat JBoss Fuse' to 'Red Hat Fuse' troughout config

- requirements.json
before everyone forgets and we get 3.3 instead 3.4
> Fix CDK dmUrl

- browser/app.css
- browser/pages/welcome/controller.js
- browser/pages/welcome/welcome.html
- package-lock.json
- test/unit/pages/welcome/controller-test.js
Fix #1390 
- **This will show if there is a new version available to download**
- **This will show Check for version and message if it is current version.**
> Css update for version update on welcome page
